---
title: "PubH 7462 A8"
author: "Jeannette Sample"
format: 
  html:
    embed-resources: true
editor: visual
---

```{r}
#| echo: false
#| message: false
#| warning: false

library(tidyverse)
library(tidycensus)
library(tigris)
library(plotly)
library(sf)
library(ggthemes)

```


```{r}
#| echo: false
#| warning: false
## Load the API key
api_key <- Sys.getenv("TIDYCENSUS")

## Produce the map
census_api_key(api_key)
options(tigris_use_cache = TRUE)
```

## Task 1.3) ggplotly of Hennepin County

```{r}
#| echo: false
#| warning: false
hen_house.df <- get_acs(
  geography = "tract",
  variables = "B25077_001", #Code for median house value
  state     = "MN",
  county    = "Hennepin",
  year      = 2020,
  geometry  = TRUE,
  cb        = FALSE
) 

#Add a text label 
hen_house_plotly.df <- hen_house.df %>%
  mutate(
    tract      = str_split(NAME, ",") %>%
      map_chr(1) %>%
      str_remove("Census Tract "),
    text_label = str_c(
      "Tract: ",
      tract,
      "\nMedian House Value: ",
      scales::dollar(estimate)
    )
  )

#Generate the ggplot
house.gg <- ggplot() + 
  geom_sf(data = hen_house_plotly.df, 
          aes(fill = estimate, text = text_label),
          colour = "black", size = 0.1) + 
  labs(title = "Hennepin County, MN 2020 ACS Median House Value") + 
  scale_fill_viridis_c("Median House Value", labels = scales::dollar) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )


#Display
ggplotly(house.gg,
         tooltip = "text",
         height  = 600,
         width   = 800) %>%
  style(hoveron = "fills")
```
